# coding=utf-8

# Created by Deserts
# email: i@panjunwen.com
# site: https://panjunwen.com/
# date: 2016-08-19
import urllib.request, urllib.error, urllib.parse

import requests
import time
from bs4 import BeautifulSoup
import re
import random
import datetime
from captcha import captcha
import io
from PIL import Image


class SeatReservation(object):
    """ Seat class:
        @ param url: Leosys' URL, e.g.http://202.206.242.87/, notice the "/"
        !NOTICE: You'd better check the seat id (object.seat!=0)
                 when an object is created,
                 because if the param seat is invalid,
                 the variable seat of the object will be seted to 0.
    """

    def __init__(self, url):
        self.url = url
        self.session = requests.session()
        self.reserveStatus = False
        self.date = self.getDate()

    '''
        login process
        two functions
        login & check status
    '''
    def login(self, username=None, password=None):
        '''
            return a status code.
            0:  login successfully
            1:  wrong username
            2:  wrong password
            -1: network is unreachable
            !NOTICE:
            username and password MUST be provided the first time
        '''
        if username is not None:
            self.userInfo = {
                "username": username,
                "password": password,
                "captcha": "",
                # 添加于2018/05/13
                "": "登录"
            }
        captchaUrl = self.url + "simpleCaptcha/captcha"
        loginUrl = self.url + "auth/signIn"
        header = {
            "User-Agent": "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.13 Safari/537.36",
            "Referer": "http://www.v2ex.com/signin"
        }
        while True:
            try:
                '''
                此处py2转py3的时候
                获取的captchaImg从str变成了byte
                所以我们添加了一步转换
                '''
                captchaImg = self.session.get(captchaUrl, headers=header)
                #captchaImgStr = bytes.decode(captchaImg.content, "ISO-8859-1")
                imfile = io.BytesIO(captchaImg.content)
                image = Image.open(imfile)
                # 这里是可以save的
                image.save("a.png", "PNG")

                self.userInfo["captcha"] = captcha(captchaImg.text)
                res = self.session.post(url=loginUrl, data=self.userInfo, headers=header)
            except requests.exceptions.ConnectionError as e:
                print(e)
                return -1
            if self.loginStatusCheck(res):
                return 0
            msg = re.findall('showmsg."(.*)",', res.text)
            if msg:
                msg = msg[0]
                print(msg)
                if msg == "登录失败: 用户不存在":
                    return 1
                elif msg == "登录失败: 密码不正确":
                    return 2
        return -1

    def loginStatusCheck(self, response=None):
        '''
            check if login successfully
        '''
        header = {
            "User-Agent": "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.13 Safari/537.36",
            "Referer": "http://www.v2ex.com/signin"
        }
        if response is None:
            response = self.session.get(self.url, headers=header)
        return response.text[1] != "!"

    '''
        book process
        reserve(): main thread of book seat
        defraud(): stimulate the post process of an internet explorer
                   update on 2018/05/13
    '''
    def reserve(self, seat, start, end):
        '''
            reserve a seat.
            !NOTICE：
            @ param seat should be a string generated by getSeatID
            @ param start, end: start and end time of minutes.
                                e.g. 8:00-13:00, start = 480, end = 780
            return a status code.
            0: reserve successfully
            1: reached the limit, can't reserve
            2: the specific seat has been reserved by another user
            3: the system has not been opened up.
            4: the account is limitted
            -1: unkown error
        '''
        floorInfo = {
            "id": "1"
        }
        timeInfo = {
            "id": seat,
            "date": self.date
        }
        endTimeInfo = {
            "start": start,
            "seat": seat,
            "date": self.date
        }
        seatInfo = {
            "date": self.date,
            "seat": seat,
            "start": start,
            "end": end,
            "captcha": ""
        }
        header = {
            "User-Agent": "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.13 Safari/537.36",
            "Referer": "http://www.v2ex.com/signin"
        }
        # post data and parse the response.
        try:
            '''
            defraud(): stimulate the post process of an internet explorer
            update on 2018/05/13
            '''
            '''
            下面这一段应该可以不用赋值直接执行吧，修改后见155-157行
            # choose building map by default is 1
            # building_res = self.session.post(url=(self.url + "mapBook/ajaxGetFloor"), data=floorInfo, headers=header)
            # choose seat map
            # seat_res = self.session.post(url=(self.url + "freeBook/ajaxGetTime"), data=timeInfo, headers=header)
            # choose end time map
            # building_res = self.session.post(url=(self.url + "freeBook/ajaxGetEndTime"), data=endTimeInfo,
            #                                 headers=header)
            '''
            self.session.post(url=(self.url + "mapBook/ajaxGetFloor"), data=floorInfo, headers=header)
            self.session.post(url=(self.url + "freeBook/ajaxGetTime"), data=timeInfo, headers=header)
            # this is where I add the captcha when the post method has been altered
            captchaImg = self.session.get(self.url + "simpleCaptcha/captcha", headers=header)
            self.session.post(url=(self.url + "freeBook/ajaxGetEndTime"), data=endTimeInfo, headers=header)
            seatInfo["captcha"] = captcha(captchaImg.content)
            # ... fuck
            res = self.session.post(url=(self.url + "selfRes"), data=seatInfo, headers=header)
            soup = BeautifulSoup(res.text, "lxml")
            info = soup.dd.text
        except:
            info = None
        print("post data: ", seatInfo)
        # deal with the response
        infoSlice = info[:4]
        if info == None:
            return 5
        if info[:3] == "凭证号" or infoSlice == "已有1个有效预":
            self.reserveStatus = True
            return 0
        elif infoSlice == "网上预约请求过":
            return 1
        elif infoSlice == "预约失败":
            return 2
        elif infoSlice == "系统可预约时间":
            return 3
        elif infoSlice == "对不起, 您的":
            return 4
        else:
            return -1

    def getSeatID(self, room, seat):
        '''
            return a seat id(string) which is used in the system.
            if it returns 0, please make sure the room and seat
            number is right.
            @ param room: int
            @ param seat: int
        '''
        header = {
            "User-Agent": "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.13 Safari/537.36",
            "Referer": "http://www.v2ex.com/signin"
        }
        dt = self.date
        url = self.url + "mapBook/getSeatsByRoom?room=%d&date=%s" % (room, dt)
        res = self.session.get(url, headers=header)
        soup = BeautifulSoup(res.text, "lxml")
        li_tags = soup.find_all("li")
        li_tags = [tag for tag in li_tags if tag.a is not None]
        for tag in li_tags:
            if int(tag.a.contents[0]) == seat:
                return tag.get("id")[5:]
        return 0

    def getDate(self):
        '''
            return a string of date of the next day,
            e.g. return "2016-08-20" when run this method on Aug 19.
        '''
        tm = time.localtime()
        date = str(tm[0]) + "-" + str(tm[1]) + "-" + str(tm[2] + 1)
        return date

    def myReservation(self):
        '''
            return a text about my reservation
        '''
        header = {
            "User-Agent": "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.13 Safari/537.36",
            "Referer": "http://www.v2ex.com/signin"
        }
        url = self.url + "history?type=SEAT"
        res = self.session.get(url, headers=header)
        soup = BeautifulSoup(res.text, "lxml")
        return soup.dt.text + "\n" + soup.dd.text.strip()

    def getSeatList(self, room):
        '''
            return a list of all available seats.
            must provide a room id.
        '''
        header = {
            "User-Agent": "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.13 Safari/537.36",
            "Referer": "http://www.v2ex.com/signin"
        }
        rm = str(room)
        dt = self.date
        url = self.url + "mapBook/getSeatsByRoom?room=%s&date=%s" % (rm, dt)
        res = self.session.get(url, headers=header)
        seatList = re.findall('>(\d+)</code', res.text)
        if seatList:
            return seatList
        else:
            return None

    def randomReserve(self, room, start, end):
        '''
            reserve a seat randomly.
        '''
        seats = self.getSeatList(room)
        if seats is not None:
            random.shuffle(seats)
            for seat in random:
                seat = self.getSeatID()
                status = self.reserve(seat, start, end)
                if status < 2:
                    return status
        return None

    def autoReserve(self, schedtime, room, seat, start, end, randRsv=False):
        '''
            reserve the specific seat after timeDelta seconds.
            @ param schedtime is a time, whose type is "datetime".
            If the param randRsv is True, it will randomly
             reserve a seat in the provided room.
        '''
        now = datetime.datetime.now()
        if now > schedtime:
            return None
        timeDelta = (schedtime - now).seconds
        time.sleep(timeDelta)
        # sleep timeDelta seconds then reserve
        # check account status
        if self.loginStatusCheck() is False:
            self.login()
        while True:
            status = self.reserve(seat, start, end)
            if status == 2 and randRsv:
                return self.randomReserve(room, start, end)
            if status != 3:
                break
        return status
